In [1]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [2]:
import numpy as np

In [3]:
np.__version__ # to check the version

'1.26.4'

In [4]:
# create a list

In [5]:
my_list =[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [6]:
type(my_list)

list

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [11]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [12]:
np.arange(10,30,3)

array([10, 13, 16, 19, 22, 25, 28])

In [13]:
np.arange(10,30,30,3)# it only has start stop and step

TypeError: Cannot interpret '3' as a data type

In [14]:
np.arange(20,10) #1sr argument should be less than 2nd aurgument

array([], dtype=int32)

In [ ]:
np.arange(-20,8)

In [ ]:
n = np.arange(-20,8)

In [ ]:
np.zeros()

In [ ]:
np.zeros(3)

In [ ]:
np.zeros(3, dtype=int)

In [ ]:
z=np.zeros(3)
z

In [ ]:
np.zeros((2,2)) # 2d array

In [ ]:
np.zeros((3,3), dtype=int) # 3d matrix

In [ ]:
nd=np.zeros((5,9), dtype=int) # n dimensions matrix
nd

In [ ]:
np.ones(3)

In [ ]:
np.ones((10,10), dtype=int)

In [ ]:
np.threes(3) #3 is not function of np

In [ ]:
nd

In [ ]:
rand(3,2)

In [ ]:
random.rand(3,2)

In [ ]:
np.random.rand(2) # generates float random num 

In [ ]:
np.random.rand(3)

In [ ]:
np.random.rand(2,3)

In [ ]:
np.random.randint(3)#generate randon num bw 0-2

In [ ]:
np.random.randint(2,10)#generate randon num bw 2-9

In [ ]:
np.random.randint(2,10,3)#generate 3 randon num bw 2-9

In [ ]:
np.random.randint(10,40,(10,10))# generate random num bw 10-39 with 10*10 matrix(rows and colums)

In [ ]:
m=np.random.randint(10,40,(10,10))   #store in m and run
m

In [ ]:
arr

In [ ]:
arr.reshape(2,3) # reshapes and arranges in 2*3 matrix

In [ ]:
arr.reshape(3,3) 

In [ ]:
arr.reshape(6,1)

In [ ]:
arr.reshape(1,6)

In [ ]:
b= np.random.randint(10,20,(5,4))
b

In [ ]:
b[:] # slicing

In [ ]:
b[1:4]

In [ ]:
b[-1:]#left side will print from it

In [ ]:
b[:-1]#right side will print till before it

In [ ]:
b[:-2] #print first 3 rows

In [ ]:
b[1:4] #print from 1 to 3    #slice (:) will give entire row and column

In [ ]:
b[1,-1] # prints only the num in 1 row -1 num(the num in that rows colum) (,)

In [ ]:
arr.max()

In [ ]:
arr.min()

In [ ]:
mat = np.arrange(0,100).reshape(10,10)